name: Run Tests

on:
  push:
    branches: [ master ]
  pull_request:

permissions:
  contents: read

jobs:

  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@44c2b7a8a4ea60a981eaca3cf939b5f4305c123b # v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '^1.19'

    - name: Test
      run: go test -race -v ./...
